version: '3'

services:
  nawst-api:
    image: nawst_api:latest
    container_name: nawst_api
    working_dir: /app
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile.development
    ports: 
      - "3000:3000"
    networks:
      - nawst-network
    volumes:
      - ../:/app:delegated

  nawst-database:
    image: postgres:latest
    container_name: nawst_database
    ports:
      - "5432:5432"
    networks:
      - nawst-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

networks:
  nawst-network:
      driver: bridge